# Generated by Django 4.2.3 on 2023-07-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0004_alter_department_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.CreateModel(
            name='Prerequisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.course', verbose_name='الكورس')),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='university_app.course', verbose_name='المتطلبات')),
            ],
            options={
                'verbose_name': 'متطلب',
                'verbose_name_plural': 'المتطلبات',
            },
        ),
    ]
